name: DevOps CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build backend Docker image
        run: docker build -t backend ./backend

      - name: Build frontend Docker image
        run: docker build -t frontend ./frontend

      - name: Run containers
        run: |
          docker-compose up -d
          sleep 15

      - name: Test backend API
        run: curl http://localhost:5000/api/data
